name: es4j-publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: publish-maven-central-packages
        run: mvn --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${secrets.OSSRH_USERNAME}}
          MAVEN_PASSWORD: ${secrets.OSSRH_PASSWORD}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
